apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    release: "0"

  ports:
    - name: http
      port: 80 #service port
      targetPort: 80  # POD port#defaults to value of port as above
      nodePort: 30080 #presented to external world.used to access the pod

  type: NodePort
